### ISSUE TITLE
Does the Power BI PUSH dataset support BIM files from an Analysis Server project

### ISSUE THREAD

**Issue by sdg002** [sql-bi/Pbi-PushDataset#3]
Can I use the BIM file generated by an Analysis Server project in Visual Studio?  

This way, I get to GIT control my model file and do CI/CD and Pull Request reviews for any model changes.  
The binary nature of PBIX/PBIT makes it very hard to do a sensible quality control during development time.

Thanks,
Sau

**Comment by marcosqlbi** [comment]
Yes of course! We show how to start from a Power BI model because it is more popular, but starting from a BIM file is the way to go!
