### ISSUE TITLE
What do we mean by "Inactive relationships are not supported" in your article on Push Datasets?

### ISSUE THREAD

**Issue by sdg002** [sql-bi/Pbi-PushDataset#4]
Hi All,
I like the idea of push datasets. I have been following your wonderful guidance in the link below:
https://www.sqlbi.com/articles/implementing-real-time-updates-in-power-bi-using-push-datasets-instead-of-directquery/

In this article you have specified the following:
![image](https://user-images.githubusercontent.com/20245330/147245677-72c5c235-1498-461d-8c65-56c8bdd5c378.png)

Please help me understand the deeper implication of this limitation. 

## Scenario 1
Since PBI supports only 1 active relationship between a parent and child table- this effectively rules out the possibility of some parent table having relationships to more than 1 child table.

I cannot have a **Products** table which is referenced by **Sales** table and also by **Orders** table.

## Scenario 2
Does it mean , that I cannot have a more than 1 relationship between the 2 tables. E.g.  OrdersTable and a DateTable could have multiple relationships. (OrderdReceivedDate , OrderFullFilmentDate)

**Comment by marcosqlbi** [comment]
Scenario 1 is supported (Products 1-* Sales, Products 1-* Orders).
Scenario 2 is not supported (Products 1-* Sales[OrderDate] but you cannot create Products 1-* Sales[DeliveryDate]).
A workaround for scenario 2 is using TREATAS: https://www.sqlbi.com/articles/propagate-filters-using-treatas-in-dax/
