### ISSUE TITLE
Operation returned an invalid status code 'Unauthorized'

### ISSUE THREAD

**Issue by RaulRuizCorredor** [sql-bi/Pbi-PushDataset#7]
Hi,

I am stack, I run the script and I am gettig the following error message:

** PUBLISH model **
Publish-PushDataset: One or more errors occurred. (Operation returned an invalid status code 'Unauthorized')

Mention that I followed all the steps and configured the app inside azure and grant privileges in Azure and Power BI Service. What I am doing wrong?

**Comment by marcosqlbi** [comment]
It seems a permission issue. Are you publishing on a workspace? It would be useful to understand whether you have an error in authentication (see Azure configuration) or during the publishing (it could be a Power BI issue).

**Comment by Ypf485** [comment]
the same issue seems to be taking place for me too could you kindly list what are the key permissions we need to take care in Azure active directory, enterprise application and power bi admin portal to use the Publish feature

**Comment by marcosqlbi** [comment]
@wnzn try to publish to a specific workspace, not to "my workspace"

**Comment by wnzn** [comment]
Thanks for your response! I'm publishing to a specific workspace (of which I'm an owner, hence 'my'). Do I need to grant any permissions on the app registration in Azure AD?

**Comment by marcosqlbi** [comment]
The user account (or the service principal) that you use for publishing must have at least member access to the workspace.

**Comment by wnzn** [comment]
Okay, well that's the case as well here. My guess now is that API access might be limited to a specific security group. I have tested this on a separate tenant and apparently you can add service principals to a workspace even if this setting is enabled but you can't use that service principal to access it. I'll post back when I have more information.

**Comment by wnzn** [comment]
Just came to add that my guess was correct: after adding the service principal to the correct group, it works perfectly. Thanks @marcosqlbi for your ideas.

**Comment by marcosqlbi** [comment]
Great - thanks for closing the loop!
